### ISSUE TITLE
Controller Tests brechen ab mit PDOException: SQLSTATE[08004] [1040] Too many connections

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#317]
## Beschreibung

Beim Ausführen der Integrations- bzw. Controller-Tests kommt es zum folgenden Fehler:

````
PHP Notice:  PDOException: SQLSTATE[08004] [1040] Too many connections in D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27
Stack trace:
#0 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(27): PDO->__construct('mysql:host=192....', 'root', 'pwd', Array)
#1 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.php(25): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=192....', 'root', 'pwd', Array)
#2 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(356): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'pwd', Array)
#3 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(420): Doctrine\DBAL\Connection->connect()
#4 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(380): Doctrine\DBAL\Connection-> in D:\...\module\ErrorHandling\src\ErrorHandling\Handler\ErrorHandler.php on line 59
PHP Stack trace:
PHP   1. ErrorHandling\Module->ErrorHandling\{closure}() D:\...\module\ErrorHandling\Module.php:0
PHP   2. ErrorHandling\Handler\ErrorHandler->handle() D:\...\module\ErrorHandling\Module.php:51
PHP   3. trigger_error() D:\...\module\ErrorHandling\src\ErrorHandling\Handler\ErrorHandler.php:59
PDOException: SQLSTATE[08004] [1040] Too many connections in D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27
Stack trace:
#0 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(27): PDO->__construct('mysql:host=192....', 'root', 'pwd', Array)
#1 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.php(25): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=192....', 'root', 'pwd', Array)
#2 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(356): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', 'pwd', Array)
#3 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(420): Doctrine\DBAL\Connection->connect()
#4 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(380): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#5 D:\...\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(324): Doctrine\DBAL\Connection->detectDatabasePlatform()
#6 D:\...\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(789): Doctrine\DBAL\Connection->getDatabasePlatform()
#7 D:\...\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(635): Doctrine\ORM\Mapping\ClassMetadataFactory->getTargetPlatform()
#8 D:\...\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(162): Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping(Object(Doctrine\ORM\Mapping\ClassMetadata))
#9 D:\...\vendor\doctrine\persistence\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(304): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#10 D:\...\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataFactory.php(78): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Base\\DataObject...')
#11 D:\...\vendor\doctrine\persistence\lib\Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory.php(183): Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata('Base\\DataObject...')
#12 D:\...\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php(283): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Base\\DataObject...')
#13 D:\...\vendor\doctrine\orm\lib\Doctrine\ORM\Repository\DefaultRepositoryFactory.php(44): Doctrine\ORM\EntityManager->getClassMetadata('Base\\DataObject...')
#14 D:\...\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php(713): Doctrine\ORM\Repository\DefaultRepositoryFactory->getRepository(Object(Doctrine\ORM\EntityManager), 'Base\\DataObject...')
#15 D:\...\module\Order\src\Order\Mapper\UserMapper.php(18): Doctrine\ORM\EntityManager->getRepository('Base\\DataObject...')
#16 D:\...\module\Order\src\Order\Service\UserService.php(56): Order\Mapper\UserMapper->findOneByUsername('undefined')
#17 D:\...\module\Authentication\src\Authentication\Adapter\DbTable.php(39): Order\Service\UserService->findOneByUsername('undefined')
#18 D:\...\vendor\zendframework\zend-authentication\src\AuthenticationService.php(112): Authentication\Adapter\DbTable->authenticate()
#19 D:\...\module\Authentication\Module.php(47): Zend\Authentication\AuthenticationService->authenticate()
#20 D:\...\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(764): Authentication\Module->Authentication\{closure}(Object(Zend\ServiceManager\ServiceManager), 'AuthenticationS...', NULL)
#21 D:\...\vendor\zendframework\zend-servicemanager\src\ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('AuthenticationS...')
#22 D:\...\module\Application\Module.php(36): Zend\ServiceManager\ServiceManager->get('AuthenticationS...')
#23 D:\...\vendor\zendframework\zend-eventmanager\src\EventManager.php(322): Application\Module->onBootstrap(Object(Zend\Mvc\MvcEvent))
#24 D:\...\vendor\zendframework\zend-eventmanager\src\EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#25 D:\...\vendor\zendframework\zend-mvc\src\Application.php(161): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#26 D:\...\vendor\zendframework\zend-mvc\src\Application.php(273): Zend\Mvc\Application->bootstrap(Array)
#27 D:\...\vendor\zendframework\zend-test\src\PHPUnit\Controller\AbstractControllerTestCase.php(191): Zend\Mvc\Application::init(Array)
#28 D:\...\vendor\zendframework\zend-test\src\PHPUnit\Controller\AbstractControllerTestCase.php(205): Zend\Test\PHPUnit\Controller\AbstractControllerTestCase->getApplication()
#29 D:\...\module\Base\src\Test\AbstractControllerTest.php(37): Zend\Test\PHPUnit\Controller\AbstractControllerTestCase->getApplicationServiceLocator()
#30 D:\...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(591): Base\Test\AbstractControllerTest->__construct()
#31 D:\...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(882): PHPUnit\Framework\TestSuite::createTest(Object(ReflectionClass), 'testInputNoneOu...')
#32 D:\...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(187): PHPUnit\Framework\TestSuite->addTestMethod(Object(ReflectionClass), Object(ReflectionMethod))
#33 D:\...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(290): PHPUnit\Framework\TestSuite->__construct(Object(ReflectionClass))
#34 D:\...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(377): PHPUnit\Framework\TestSuite->addTestSuite(Object(ReflectionClass))
#35 D:\...\vendor\phpunit\phpunit\src\Framework\TestSuite.php(403): PHPUnit\Framework\TestSuite->addTestFile('D:\\workspace\\de...')
#36 D:\...\vendor\phpunit\phpunit\src\Util\Configuration.php(1014): PHPUnit\Framework\TestSuite->addTestFiles(Array)
#37 D:\...\vendor\phpunit\phpunit\src\Util\Configuration.php(918): PHPUnit\Util\Configuration->getTestSuite(Object(DOMElement), Array)
#38 D:\...\vendor\phpunit\phpunit\src\TextUI\Command.php(837): PHPUnit\Util\Configuration->getTestSuiteConfiguration(NULL)
#39 D:\...\vendor\phpunit\phpunit\src\TextUI\Command.php(159): PHPUnit\TextUI\Command->handleArguments(Array)
#40 D:\...\vendor\phpunit\phpunit\src\TextUI\Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#41 D:\...\vendor\phpunit\phpunit\phpunit(53): PHPUnit\TextUI\Command::main()
#42 {main}
````

Vermutlich werden Datenbank-Verbindungen nicht sauber geschlossen.

Als schneller Workaround wurde in der Vergangenheit der Wert der MySQL-Einstellung `max_connections` hochgesetzt. So wuchs er aber mit jedem weiteren Test und ist mittlerweile `>300`. Nun soll das Problem auf eine saubere Weise behoben werden.

**Comment by automatix** [comment]
Die Anzahl der gleichzeitig geöffneten Datenbank-Verbindungen wurde etwas reduziert, sodass der Fehler vorerst nicht mehr auftritt. Es soll aber zu einem späteren Zeitpunkt die Ursache dieses Verhaltens gefunden und das Problem sauber gelöst werden.
