### ISSUE TITLE
Beim Aufruf eines Formulars tritt ein "Service not found"-Fehler

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#347]
## Beschreibung

Beim Aufruf eines Formulars treten Fehler, wie dieser auf:

```
Ein Fehler ist aufgetreten
An error occurred during execution; please try again later.
Zusätzliche Information:
Laminas\ServiceManager\Exception\ServiceNotCreatedException
Datei:
/.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:777
Meldung:
Service with name "Order\Controller\Process" could not be created. Reason: A plugin by the name "Order\Form\Fieldset\PhysicalConnectioncdEndToEnd" was not found in the plugin manager Laminas\Form\FormElementManager\FormElementManagerV3Polyfill
Stapelüberwachung:
#0 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Order\\Controlle...')
#1 /.../autofit/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get('Order\\Controlle...')
#2 /.../autofit/vendor/laminas/laminas-mvc/src/DispatchListener.php(103): Laminas\ServiceManager\AbstractPluginManager->get('Order\\Controlle...')
#3 /.../autofit/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#4 /.../autofit/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#5 /.../autofit/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#6 /.../autofit/public/index.php(33): Laminas\Mvc\Application->run()
#7 {main}
Vorherige Ausnahme:
Laminas\Form\Exception\InvalidElementException
Datei:
/.../autofit/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerTrait.php:64
Meldung:
A plugin by the name "Order\Form\Fieldset\PhysicalConnectioncdEndToEnd" was not found in the plugin manager Laminas\Form\FormElementManager\FormElementManagerV3Polyfill
Stapelüberwachung:
#0 /.../autofit/vendor/laminas/laminas-form/src/Factory.php(128): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->get('Order\\Form\\Fiel...')
#1 /.../autofit/vendor/laminas/laminas-form/src/Fieldset.php(165): Laminas\Form\Factory->create(Array)
#2 /.../autofit/module/Order/src/Order/Form/Fieldset/AbstractLogicalConnectionFieldset.php(44): Laminas\Form\Fieldset->add(Array)
#3 /.../autofit/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerV3Polyfill.php(323): Order\Form\Fieldset\AbstractLogicalConnectionFieldset->init()
#4 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(785): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit(Object(Laminas\ServiceManager\ServiceManager), Object(Order\Form\Fieldset\LogicalConnectionCdFieldset))
#5 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Order\\Form\\Fiel...')
#6 /.../autofit/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get('Order\\Form\\Fiel...')
#7 /.../autofit/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerTrait.php(73): Laminas\ServiceManager\AbstractPluginManager->get('Order\\Form\\Fiel...', Array, true)
#8 /.../autofit/vendor/laminas/laminas-form/src/Factory.php(128): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->get('Order\\Form\\Fiel...')
#9 /.../autofit/vendor/laminas/laminas-form/src/Fieldset.php(165): Laminas\Form\Factory->create(Array)
#10 /.../autofit/module/Order/src/Order/Form/Fieldset/AbstractFileTransferRequestFieldset.php(89): Laminas\Form\Fieldset->add(Array)
#11 /.../autofit/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerV3Polyfill.php(323): Order\Form\Fieldset\AbstractFileTransferRequestFieldset->init()
#12 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(785): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit(Object(Laminas\ServiceManager\ServiceManager), Object(Order\Form\Fieldset\FileTransferRequestCdFieldset))
#13 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Order\\Form\\Fiel...')
#14 /.../autofit/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get('Order\\Form\\Fiel...')
#15 /.../autofit/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerTrait.php(73): Laminas\ServiceManager\AbstractPluginManager->get('Order\\Form\\Fiel...', Array, true)
#16 /.../autofit/vendor/laminas/laminas-form/src/Factory.php(128): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->get('Order\\Form\\Fiel...')
#17 /.../autofit/vendor/laminas/laminas-form/src/Form.php(188): Laminas\Form\Factory->create(Array)
#18 /.../autofit/module/Order/src/Order/Form/OrderForm.php(66): Laminas\Form\Form->add(Array)
#19 /.../autofit/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerV3Polyfill.php(323): Order\Form\OrderForm->init()
#20 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(785): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit(Object(Laminas\ServiceManager\ServiceManager), Object(Order\Form\OrderForm))
#21 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Order\\Form\\Orde...')
#22 /.../autofit/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get('Order\\Form\\Orde...')
#23 /.../autofit/vendor/laminas/laminas-form/src/FormElementManager/FormElementManagerTrait.php(73): Laminas\ServiceManager\AbstractPluginManager->get('Order\\Form\\Orde...', Array, true)
#24 /.../autofit/module/Order/src/Order/Controller/Factory/ProcessControllerFactory.php(34): Laminas\Form\FormElementManager\FormElementManagerV3Polyfill->get('Order\\Form\\Orde...')
#25 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(770): Order\Controller\Factory\ProcessControllerFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Order\\Controlle...', NULL)
#26 /.../autofit/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('Order\\Controlle...')
#27 /.../autofit/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get('Order\\Controlle...')
#28 /.../autofit/vendor/laminas/laminas-mvc/src/DispatchListener.php(103): Laminas\ServiceManager\AbstractPluginManager->get('Order\\Controlle...')
#29 /.../autofit/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#30 /.../autofit/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#31 /.../autofit/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#32 /.../autofit/public/index.php(33): Laminas\Mvc\Application->run()
#33 {main}
```

**Comment by automatix** [comment]
Das Problem ist die Groß- und Kleinschreibung. Bei einigen Klassen ist deren genaue Ausprägung davon abhängig, welcher Verbindungstyp und welche Endpoint-Typen angefragt wurden. Diese Parameter werden dem URL bzw. der Route entnommen. Dann wird z.B. eine Klasse wie `PhysicalConnection{Cd}EndToEnd`, `EndpointCdTandemSource` oder `EndpointCdAs400Target` insanziiert. Während die Klassennamen camel-cased sind, sind die Verbindungs- und die Endpoint-Typen intern kleingeschrieben gespeichert. Offenbar werden sie bem Zusammenstellen des Klassennamens nicht klassennamengerecht (z.B. `ftgw -> Ftgw`) manipuliert, wodurch Klassennamen-Strings wie "PhysicalConnection**c**dEndToEnd" (astatt von "PhysicalConnection**C**dEndToEnd") entstehen. Die Klassendatei "PhysicalConnection**c**dEndToEnd.php" (um bei dem Beispiel zu blieben) existiert nicht (sondern es existiert die "PhysicalConnection**C**dEndToEnd.php"). Deshalb wird sie auf dem neuen Linux-Server nicht gefunden. (Genauso wird sie auf der Linux-VM der lokalen Entwicklungsumgebung nicht gefunden.) Das verursacht einen "Service not found"-Fehler.

Da Windows case insensitive ist, führte das auf den alten Windows-Servern zu keinen Problemen. Aus dem selben Grund fiel das auch in der lokalen Entwicklungsumgebung nicht auf, weil dort das Projekt-Verzeichnis in einem Shared Folder liegt, wo offensichtlich die Host-Regeln (also die Windows-Regeln) gelten.

**Comment by automatix** [comment]
gefixt
