### ISSUE TITLE
Error: Call to a member function getServiceInvoice() on null

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#350]
## Beschreibung

Auf der Seite "Bestellungen" bzw. "Meine Bestellungen" tritt folgender Fehler auf:

```
2020-06-12T10:31:33+02:00 CRIT (2): Error: Call to a member function getServiceInvoice() on null in /var/www/.../autofit/module/Order/view/partials/list/summary.phtml:165
Stack trace:
#0 /var/www/.../autofit/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include()
#1 /var/www/.../autofit/vendor/laminas/laminas-view/src/Helper/Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, NULL)
#2 [internal function]: Laminas\View\Helper\Partial->__invoke('/partials/list/...', Array)
#3 /var/www/.../autofit/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Laminas\View\Helper\Partial), Array)
#4 /var/www/.../autofit/module/Order/view/order/process/list-my-orders.phtml(57): Laminas\View\Renderer\PhpRenderer->__call('partial', Array)
#5 /var/www/.../autofit/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/develo...')
#6 /var/www/.../autofit/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#7 /var/www/.../autofit/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#8 /var/www/.../autofit/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#9 /var/www/.../autofit/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#10 /var/www/.../autofit/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/.../autofit/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#12 /var/www/.../autofit/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#13 /var/www/.../autofit/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#14 /var/www/.../autofit/public/index.php(33): Laminas\Mvc\Application->run()
#15 {main} {"error-reference":"a4b57e6","request-uri":"http://autofit...loc/order/list-own"}
```

## Ursache

Ende 2017 wurde die Datenbank-Struktur angepasset. Es kamen folgende Änderungen:

- Die Tabelle `file_transfer_request_service_invoice_position` wurde hinzugefügt. Dort werden die verwendeten LSPs abgespeichert.
- Die Tabelle `service_invoice_position` wurde um die Spalte `type` erweitert.

Das Befüllen der Tabelle `file_transfer_request_service_invoice_position` und der Spalte `service_invoice_position.type` wurden SQL-Queries entwickelt.

Der Code wurde ensprechend angepasst. So werden beispielsweise die LSPs des Antrags für die Anzeige aus der `file_transfer_request_service_invoice_position` ausgelesen.

Das PROD-System (der Code und die Datenbank) wurde damals (aufgrund von Account-Sperrung) nicht aktualisiert. Als am 11.06.2020 im Zuge der Migration die Daten-Struktur aktualisiert wurde, wurden zwar die Tabelle `file_transfer_request_service_invoice_position` und die Spalte `service_invoice_position.type` hinzugefügt, aber, da kein Migrationssktipt ausgeführt wurde, sind sie leer. Deshalb werd jetzt beim Aufruf einer Bestellung ihre LSPs nicht gefunden, die `$fileTransferRequest->getServiceInvoicePositionBasic()` liefert anstatt eines `ServiceInvoicePosition`-Objekts `null` und der nächste Call daran führt zu einem "Call to a member function on null"-Fehler.

## Lösung

Die Tabelle `file_transfer_request_service_invoice_position` und die Spalte `service_invoice_position.type` nach der selben Logik wie Ende 2017 befüllen.

**Comment by automatix** [comment]
gefixt
